# Generated by Django 4.0.3 on 2022-03-13 21:12

# migrations
# 모델 정보, 스키마 변경이있을떄마다 그 변화를 기록해주는 역할을함
# 모델 파일에 속성을 추가하거나 모델을 새로 만들경우 makemigrations 을 해주어야하며
# migrations 파일에 새로운 변화를 저장하는 새 파일이  하나 더 생김

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.option')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.topic')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.topic'),
        ),
    ]


